# Generated by Django 3.1.1 on 2020-12-18 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kerofis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='is_name_of_day',
            field=models.BooleanField(db_column='kk_anv_deiz', default=False),
        ),
        migrations.AlterField(
            model_name='location',
            name='category',
            field=models.ForeignKey(db_column='kk_rummad', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locations', to='kerofis.category'),
        ),
        migrations.AlterField(
            model_name='location',
            name='city',
            field=models.ForeignKey(db_column='kk_kumun', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locations', to='kerofis.city'),
        ),
        migrations.AlterField(
            model_name='standardizedform',
            name='location',
            field=models.ForeignKey(db_column='kss_niv', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='standardized_forms', to='kerofis.location'),
        ),
    ]
