# Generated by Django 3.1.1 on 2021-04-22 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kerofis', '0004_auto_20201218_1719'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='location',
            name='updated_by',
        ),
        migrations.AddField(
            model_name='location',
            name='bf_date',
            field=models.DateField(blank=True, db_column='kk_deiziad_bf', null=True),
        ),
        migrations.AlterField(
            model_name='informant',
            name='arrival_date',
            field=models.CharField(db_column='kt_pegoulz_er_gumun', default='', max_length=4),
        ),
        migrations.AlterField(
            model_name='informant',
            name='birthdate',
            field=models.CharField(db_column='kt_bloaz_ganedigezh', default='', max_length=4),
        ),
        migrations.AlterField(
            model_name='informant',
            name='birthplace',
            field=models.CharField(db_column='kt_lech_ganedigezh', default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='informant',
            name='cities',
            field=models.CharField(db_column='kt_kumun_titouret', default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='informant',
            name='contact',
            field=models.TextField(db_column='kt_darempred', default=''),
        ),
        migrations.AlterField(
            model_name='informant',
            name='first_name',
            field=models.CharField(db_column='kt_anv_bihan_titourer', default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='informant',
            name='last_name',
            field=models.CharField(db_column='kt_anv_titourer', default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='informant',
            name='notes',
            field=models.TextField(db_column='kt_notenn', default=''),
        ),
        migrations.AlterField(
            model_name='informant',
            name='occupation',
            field=models.CharField(db_column='kt_micher', default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='informant',
            name='surname',
            field=models.CharField(db_column='kt_lesanv', default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='location',
            name='category',
            field=models.ForeignKey(blank=True, db_column='kk_rummad', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locations', to='kerofis.category'),
        ),
        migrations.AlterField(
            model_name='location',
            name='city',
            field=models.ForeignKey(blank=True, db_column='kk_kumun', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locations', to='kerofis.city'),
        ),
        migrations.AlterField(
            model_name='location',
            name='department',
            field=models.ForeignKey(blank=True, db_column='kk_departamant', null=True, on_delete=django.db.models.deletion.SET_NULL, to='kerofis.department'),
        ),
        migrations.AlterField(
            model_name='location',
            name='etymological_note_bre',
            field=models.TextField(blank=True, db_column='kk_gerdarzh_bre', default=''),
        ),
        migrations.AlterField(
            model_name='location',
            name='etymological_note_fra',
            field=models.TextField(blank=True, db_column='kk_gerdarzh_fra', default=''),
        ),
        migrations.AlterField(
            model_name='location',
            name='formalized_date',
            field=models.DateField(blank=True, db_column='kk_deiziad_ofisielisaet', null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='formalized_proposal',
            field=models.CharField(blank=True, db_column='kk_kinnig_skoueriekaat', default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='location',
            name='ign_date',
            field=models.DateField(blank=True, db_column='kk_deiziad_ign', null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='is_public',
            field=models.BooleanField(db_column='kk_aotre_embann', default=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='notes',
            field=models.TextField(blank=True, db_column='kk_notenn_studi', default=''),
        ),
        migrations.AlterField(
            model_name='location',
            name='on_bf',
            field=models.BooleanField(db_column='kk_kartenn_bf', default=False),
        ),
        migrations.AlterField(
            model_name='location',
            name='on_ign',
            field=models.BooleanField(db_column='kk_ign', default=False),
        ),
        migrations.AlterField(
            model_name='location',
            name='proposal_author',
            field=models.TextField(blank=True, db_column='kk_goulenner', default=''),
        ),
        migrations.AlterField(
            model_name='location',
            name='reference',
            field=models.TextField(blank=True, db_column='kk_daveenn', default=''),
        ),
        migrations.AlterField(
            model_name='location',
            name='square_bf',
            field=models.CharField(blank=True, db_column='kk_karrezenn', default='', max_length=5),
        ),
        migrations.AlterField(
            model_name='phonetictranscriptionlink',
            name='link',
            field=models.FileField(db_column='kde_distagadur_enrolladenn', upload_to=''),
        ),
    ]
