# Generated by Django 3.1.1 on 2020-10-22 10:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('commun', '0002_unaccent'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrammaticalCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_bre', models.CharField(db_column='mrg_rummenn_ger_bre', max_length=40)),
                ('title_fra', models.CharField(db_column='mrg_rummenn_ger_fra', max_length=40)),
                ('abbreviation_bre', models.CharField(db_column='mrg_rummenn_ger_berradur_bre', max_length=5)),
                ('abbreviation_fra', models.CharField(db_column='mrg_rummenn_ger_berradur_fra', max_length=5)),
            ],
            options={
                'db_table': 'meurgorf_rummen_ger',
            },
        ),
        migrations.CreateModel(
            name='HistoricalOccurrence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occurence', models.TextField(db_column='msi_skouer')),
                ('occurence_normalized', models.TextField(blank=True, db_column='msi_skouer_peurunvan', default='')),
                ('litteral_year', models.CharField(db_column='msi_bloavezh', max_length=10)),
                ('year', models.PositiveSmallIntegerField(db_column='msi_bloavezh_niverel')),
                ('reference', models.TextField(db_column='msi_daveenn')),
                ('book', models.ForeignKey(db_column='msi_mammenn', null=True, on_delete=django.db.models.deletion.SET_NULL, to='commun.book')),
            ],
            options={
                'db_table': 'meurgorf_skouer_istorel',
                'ordering': ['year'],
            },
        ),
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canonic_form', models.TextField(db_column='mp_pennger')),
                ('can_be_edited', models.BooleanField(db_column='mp_aotre_embann', default=True)),
                ('on_ndbf', models.BooleanField(db_column='mp_ndbf', default=False)),
                ('on_gbahe', models.BooleanField(db_column='mp_gbahe', default=False)),
                ('definition', models.TextField(blank=True, db_column='mp_termenadur', default='')),
                ('study_notes', models.TextField(blank=True, db_column='mp_noteen_studi', default='')),
                ('etymology', models.TextField(blank=True, db_column='mp_gerdarzh', default='')),
                ('created_at', models.DateTimeField(db_column='mp_deziad_foran', default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(null=True)),
                ('usage', models.SmallIntegerField(choices=[('3', 'Very Usual'), ('2', 'Usual'), ('1', 'uncommon')], db_column='mp_implij', default='2')),
                ('old_id', models.IntegerField(null=True)),
                ('created_by', models.ForeignKey(db_column='mp_aozer', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='terms', to=settings.AUTH_USER_MODEL)),
                ('grammatical_category', models.ForeignKey(db_column='mp_rummenn_ger', on_delete=django.db.models.deletion.CASCADE, related_name='terms', to='meurgorf.grammaticalcategory')),
                ('parents', models.ManyToManyField(db_table='meurgorf_pennger_kar', related_name='_term_parents_+', to='meurgorf.Term')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'meurgorf_pennger',
            },
        ),
        migrations.CreateModel(
            name='TermSearchQuery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(db_column='me_reket', max_length=200, null=None, unique=True)),
                ('query_type', models.CharField(db_column='me_oberataer', max_length=2, null=None)),
                ('date', models.DateTimeField(db_column='me_deiziad')),
                ('counter', models.IntegerField(db_column='me_konter_goulenn', null=None)),
                ('results_number', models.IntegerField(db_column='me_konter_disoch', null=None)),
            ],
            options={
                'db_table': 'meurgorf_enklaskou',
            },
        ),
        migrations.CreateModel(
            name='Variant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variant', models.CharField(db_column='ma_adpennger', max_length=50)),
                ('term', models.ForeignKey(db_column='ma_niv', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='variants', to='meurgorf.term')),
            ],
            options={
                'db_table': 'meurgorf_adpennger',
            },
        ),
        migrations.CreateModel(
            name='PhoneticForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phonetic_form', models.TextField(db_column='md_distagadur', null=True)),
                ('phonetic_url', models.CharField(db_column='md_distagadur_enrolladenn', max_length=30, null=True)),
                ('term', models.ForeignKey(db_column='md_niv', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='phonetic_forms', to='meurgorf.term')),
            ],
            options={
                'db_table': 'meurgorf_distagadur',
            },
        ),
        migrations.CreateModel(
            name='HistoricalOccurrenceOccurrence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.ForeignKey(db_column='md_id_skouer_istorel', null=True, on_delete=django.db.models.deletion.SET_NULL, to='meurgorf.historicaloccurrence')),
                ('term', models.ForeignKey(db_column='md_niv_pennger', null=True, on_delete=django.db.models.deletion.SET_NULL, to='meurgorf.term')),
            ],
            options={
                'db_table': 'meurgorf_degouezh',
            },
        ),
        migrations.AddField(
            model_name='historicaloccurrence',
            name='terms',
            field=models.ManyToManyField(related_name='historical_occurrences', through='meurgorf.HistoricalOccurrenceOccurrence', to='meurgorf.Term'),
        ),
        migrations.CreateModel(
            name='DerivedForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(db_column='mfd_urzh')),
                ('sub_order', models.PositiveSmallIntegerField(db_column='mfd_isurzh', default=0)),
                ('form', models.TextField(db_column='mfd_stumm')),
                ('term', models.ForeignKey(db_column='mfd_niv', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='derived_forms', to='meurgorf.term')),
            ],
            options={
                'db_table': 'meurgorf_furm_deveret',
                'ordering': ['order', 'sub_order'],
            },
        ),
    ]
