# Generated by Django 3.1.1 on 2020-12-18 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meurgorf', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phoneticform',
            name='phonetic_url',
        ),
        migrations.AddField(
            model_name='phoneticform',
            name='phonetic_file',
            field=models.FileField(db_column='md_distagadur_enrolladenn', max_length=30, null=True, upload_to=''),
        ),
    ]
