# Generated by Django 3.1.1 on 2020-09-23 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meurgorf', '0002_unaccent'),
    ]

    operations = [
        migrations.RunSQL("update meurgorf_pennger set mp_implij = '1' where meurgorf_pennger.mp_ndbf = false and "
                          "meurgorf_pennger.mp_gbahe = false;",
                          reverse_sql="update meurgorf_pennger set mp_implij = '';"),
        migrations.RunSQL("update meurgorf_pennger set mp_implij = '2' where (meurgorf_pennger.mp_ndbf = true and "
                          "meurgorf_pennger.mp_gbahe = false) or (meurgorf_pennger.mp_ndbf = false and "
                          "meurgorf_pennger.mp_gbahe = true);",
                          reverse_sql="update meurgorf_pennger set mp_implij = '';"),
        migrations.RunSQL("update meurgorf_pennger set mp_implij = '3' where meurgorf_pennger.mp_ndbf = true and "
                          "meurgorf_pennger.mp_gbahe = true;",
                          reverse_sql="update meurgorf_pennger set mp_implij = '';"),
        migrations.AlterField(
            model_name='term',
            name='usage',
            field=models.SmallIntegerField(choices=[('3', 'Very Usual'), ('2', 'Usual'), ('1', 'uncommon')], db_column='mp_implij', default='2'),
        ),
        migrations.RemoveField(
            model_name='phoneticform',
            name='url',
        ),
        migrations.AddField(
            model_name='phoneticform',
            name='phonetic_url',
            field=models.CharField(db_column='md_distagadur_enrolladenn', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='phoneticform',
            name='phonetic_form',
            field=models.TextField(db_column='md_distagadur', null=True),
        ),
    ]
