# Generated by Django 3.1.1 on 2021-04-22 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meurgorf', '0002_auto_20201218_1719'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='term',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='term',
            name='updated_by',
        ),
    ]
