# Generated by Django 3.1.1 on 2020-10-22 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abbrevation', models.CharField(db_column='hm_mammenn_berradur', max_length=15, unique=True)),
                ('title', models.TextField(db_column='hm_mammenn_levr')),
                ('description', models.TextField(blank=True, db_column='hm_mammenn_deskrivadur')),
                ('is_kerofis_old', models.BooleanField(db_column='hm_mammenn_kozh', default=False)),
                ('is_kerofis_other', models.BooleanField(db_column='hm_mammenn_all', default=False)),
                ('is_kerofis_attested', models.BooleanField(db_column='hm_mammenn_testeniekaet', default=False)),
                ('is_meurgorf', models.BooleanField(db_column='hm_mammenn_meurgorf', default=False)),
                ('author', models.CharField(blank=True, db_column='hm_mammenn_aozer', default='', max_length=100)),
                ('is_active', models.BooleanField(db_column='hm_mammenn_bev', default=True)),
            ],
            options={
                'verbose_name': 'Oberenn',
                'db_table': 'hollek_mammenn',
                'ordering': ['abbrevation'],
            },
        ),
    ]
