# Generated by Django 3.1 on 2020-08-28 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commun', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'verbose_name': 'Oberenn'},
        ),
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.CharField(blank=True, db_column='hm_mammenn_aozer', default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='book',
            name='is_kerofis_attested',
            field=models.BooleanField(db_column='hm_mammenn_testeniekaet', default=False),
        ),
        migrations.AlterField(
            model_name='book',
            name='is_kerofis_old',
            field=models.BooleanField(db_column='hm_mammenn_kozh', default=False),
        ),
        migrations.AlterField(
            model_name='book',
            name='is_kerofis_other',
            field=models.BooleanField(db_column='hm_mammenn_all', default=False),
        ),
        migrations.AlterField(
            model_name='book',
            name='is_meurgorf',
            field=models.BooleanField(db_column='hm_mammenn_meurgorf', default=False),
        ),
    ]
